# Generated by Django 5.2.8 on 2026-03-08 14:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='trips.division')),
            ],
            options={
                'ordering': ['division__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upazilas', to='trips.district')),
            ],
            options={
                'ordering': ['district__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('hotel_name', models.CharField(blank=True, max_length=150)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('food_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('hotel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ticket_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.division')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.tourspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('upazila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.upazila')),
            ],
            options={
                'ordering': ['-from_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tourspot',
            name='upazila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spots', to='trips.upazila'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('division', 'name'), name='uniq_district_name_per_division'),
        ),
        migrations.AddConstraint(
            model_name='upazila',
            constraint=models.UniqueConstraint(fields=('district', 'name'), name='uniq_upazila_name_per_district'),
        ),
        migrations.AddConstraint(
            model_name='tourspot',
            constraint=models.UniqueConstraint(fields=('upazila', 'name'), name='uniq_spot_name_per_upazila'),
        ),
    ]
