# Generated by Django 5.2.8 on 2026-03-08 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_album_albumitem_communitypost_communitycomment_story_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='trips.district'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='hashtags',
            field=models.CharField(blank=True, help_text='Comma separated hashtags, e.g. #sylhet,#budget', max_length=280),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='location_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='poll_options',
            field=models.TextField(blank=True, help_text='One option per line.'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='poll_question',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('travel_question', 'Travel Question'), ('travel_experience', 'Travel Experience'), ('budget_help', 'Budget Help'), ('hotel_recommendation', 'Hotel Recommendation'), ('transport_advice', 'Transport Advice'), ('trip_plan', 'Trip Plan'), ('travel_warning', 'Travel Warning'), ('lost_found', 'Lost & Found')], default='travel_experience', max_length=40),
        ),
        migrations.CreateModel(
            name='CommunityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post_reply', 'Post Reply'), ('comment', 'Comment'), ('mention', 'Mention'), ('answer', 'Answer')], max_length=20)),
                ('message', models.CharField(max_length=240)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trips.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('helpful', 'Helpful')], default='like', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='trips.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_reaction_per_user')],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='trips.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_saved_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='uniq_saved_post_per_user')],
            },
        ),
    ]
