# Generated by Django 5.2.8 on 2026-03-08 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_communitypost_district_communitypost_hashtags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Next Trip', max_length=120)),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=220)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_date', 'reminder_time', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active', 'reminder_date', 'reminder_time'], name='trips_tripr_user_id_dc0686_idx')],
            },
        ),
    ]
