# Generated by Codex on 2026-03-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_userprofile_profile_refresh"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripreminder",
            name="spot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trip_reminders",
                to="trips.tourspot",
            ),
        ),
    ]
