# Generated by Django 5.2.8 on 2026-03-09 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_tripreminder_spot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='SettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', max_length=12)),
                ('layout_density', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable')], default='comfortable', max_length=16)),
                ('map_style', models.CharField(choices=[('roadmap', 'Roadmap'), ('terrain', 'Terrain'), ('satellite', 'Satellite')], default='roadmap', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserCommunitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_can_message', models.CharField(choices=[('no_one', 'No one'), ('followers', 'Followers Only'), ('community', 'Community Members'), ('everyone', 'Everyone')], default='followers', max_length=16)),
                ('who_can_comment', models.CharField(choices=[('no_one', 'No one'), ('followers', 'Followers Only'), ('community', 'Community Members'), ('everyone', 'Everyone')], default='everyone', max_length=16)),
                ('who_can_tag', models.CharField(choices=[('no_one', 'No one'), ('followers', 'Followers Only'), ('community', 'Community Members'), ('everyone', 'Everyone')], default='followers', max_length=16)),
                ('who_can_mention', models.CharField(choices=[('no_one', 'No one'), ('followers', 'Followers Only'), ('community', 'Community Members'), ('everyone', 'Everyone')], default='everyone', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserDataSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_enabled', models.BooleanField(default=False)),
                ('export_format', models.CharField(choices=[('zip', 'ZIP Archive'), ('json', 'JSON'), ('csv', 'CSV')], default='zip', max_length=12)),
                ('include_media_in_exports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_upload_quality', models.CharField(choices=[('optimized', 'Optimized'), ('high', 'High'), ('original', 'Original')], default='high', max_length=16)),
                ('auto_image_compression', models.BooleanField(default=True)),
                ('video_upload_limit', models.CharField(choices=[('100', '100 MB'), ('250', '250 MB'), ('500', '500 MB')], default='250', max_length=8)),
                ('external_storage_provider', models.CharField(choices=[('none', 'Keep uploads in app storage'), ('google_photos', 'Google Photos'), ('google_drive', 'Google Drive')], default='none', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('comment_alerts', models.BooleanField(default=True)),
                ('follower_alerts', models.BooleanField(default=True)),
                ('trip_reminders', models.BooleanField(default=True)),
                ('community_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_visibility', models.CharField(choices=[('private', 'Private'), ('followers', 'Followers Only'), ('public', 'Public')], default='private', max_length=16)),
                ('saved_spots_visibility', models.CharField(choices=[('private', 'Private'), ('followers', 'Followers Only'), ('public', 'Public')], default='private', max_length=16)),
                ('history_visibility', models.CharField(choices=[('private', 'Private'), ('followers', 'Followers Only'), ('public', 'Public')], default='private', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserRegionalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(choices=[('Asia/Dhaka', 'Asia/Dhaka'), ('UTC', 'UTC'), ('Asia/Kolkata', 'Asia/Kolkata'), ('Asia/Singapore', 'Asia/Singapore')], default='Asia/Dhaka', max_length=64)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=16)),
                ('currency', models.CharField(choices=[('BDT', 'Bangladeshi Taka (BDT)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('INR', 'Indian Rupee (INR)')], default='BDT', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regional_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('recovery_email', models.EmailField(blank=True, max_length=254)),
                ('recovery_phone', models.CharField(blank=True, max_length=30)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('login_alerts', models.BooleanField(default=True)),
                ('suspicious_activity_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserTravelPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(choices=[('BDT', 'Bangladeshi Taka (BDT)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('INR', 'Indian Rupee (INR)')], default='BDT', max_length=8)),
                ('default_trip_visibility', models.CharField(choices=[('private', 'Private'), ('followers', 'Followers Only'), ('public', 'Public')], default='private', max_length=16)),
                ('preferred_map_view', models.CharField(choices=[('division', 'Division View'), ('district', 'District View'), ('spot', 'Spot View')], default='district', max_length=16)),
                ('distance_unit', models.CharField(choices=[('km', 'Kilometers'), ('mi', 'Miles')], default='km', max_length=8)),
                ('default_expense_categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
