# Generated by Django 5.2.8 on 2026-03-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_userprofile_social_links_settingsauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='agency_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_source',
            field=models.CharField(choices=[('self', 'Self Trip'), ('agency', 'Agency Trip')], default='self', max_length=12),
        ),
        migrations.AddField(
            model_name='tripreminder',
            name='agency_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tripreminder',
            name='trip_source',
            field=models.CharField(choices=[('self', 'Self Trip'), ('agency', 'Agency Trip')], default='self', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('company', 'Company / Agency')], default='personal', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agency_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agency_contact_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agency_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agency_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agency_license_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agency_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_verification_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_required', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
