# Generated by Django 5.2.8 on 2026-03-09 18:54

import django.db.models.deletion
import trips.validators
from django.conf import settings
from django.db import migrations, models


def copy_legacy_direct_messages(apps, schema_editor):
    Conversation = apps.get_model("trips", "Conversation")
    Message = apps.get_model("trips", "Message")
    DirectConversation = apps.get_model("trips", "DirectConversation")
    DirectMessage = apps.get_model("trips", "DirectMessage")

    conversation_map = {}
    for legacy in DirectConversation.objects.all().order_by("id"):
        conversation = Conversation.objects.create()
        Conversation.objects.filter(id=conversation.id).update(
            created_at=legacy.created_at,
            updated_at=legacy.updated_at,
        )
        conversation.participants.set([legacy.user_one_id, legacy.user_two_id])
        conversation_map[legacy.id] = conversation.id

    for legacy_message in DirectMessage.objects.all().order_by("id"):
        new_conversation_id = conversation_map.get(legacy_message.conversation_id)
        if not new_conversation_id:
            continue
        message = Message.objects.create(
            conversation_id=new_conversation_id,
            sender_id=legacy_message.sender_id,
            content=legacy_message.body,
            is_read=legacy_message.is_read,
        )
        Message.objects.filter(id=message.id).update(created_at=legacy_message.created_at)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_communitynotification_kind_directconversation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trips.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat/', validators=[trips.validators.validate_album_media_upload])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trips.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(copy_legacy_direct_messages, noop_reverse),
    ]
