# Generated by Django 5.2.8 on 2026-03-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_conversation_message_messageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communitynotification',
            name='kind',
            field=models.CharField(choices=[('post_reply', 'Post Reply'), ('comment', 'Comment'), ('mention', 'Mention'), ('answer', 'Answer'), ('like', 'Like'), ('follow', 'Follow'), ('direct_message', 'Direct Message')], max_length=20),
        ),
    ]
