# Generated by Django 5.2.8 on 2026-03-09 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_userprofile_last_active_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitynotification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trips.conversation'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='call_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='like_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='message_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='communitynotification',
            name='kind',
            field=models.CharField(choices=[('post_reply', 'Post Reply'), ('comment', 'Comment'), ('mention', 'Mention'), ('answer', 'Answer'), ('like', 'Like'), ('follow', 'Follow'), ('direct_message', 'Direct Message'), ('call', 'Call')], max_length=20),
        ),
    ]
