# Generated by Django 5.2.8 on 2026-03-09 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_communitycomment_edited_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('help', 'Help & Questions'), ('trip_planning', 'Trip Planning'), ('budget_travel', 'Budget Travel'), ('hotels_stay', 'Hotels & Stay'), ('transport_advice', 'Transport Advice'), ('travel_guide', 'Travel Guide'), ('travel_question', 'Travel Question'), ('travel_experience', 'Travel Experience'), ('budget_help', 'Budget Help'), ('hotel_recommendation', 'Hotel Recommendation'), ('trip_plan', 'Trip Plan'), ('travel_warning', 'Travel Warning'), ('lost_found', 'Lost & Found')], default='discussion', max_length=40),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='trips.communitytag'),
        ),
        migrations.CreateModel(
            name='CommunityPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='community/posts/attachments/')),
                ('external_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('source', models.CharField(choices=[('attachment', 'Attachment'), ('inline', 'Inline Post Field')], default='attachment', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='trips.communitypost')),
            ],
            options={
                'ordering': ['sort_order', 'created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('post', 'source', 'media_type', 'sort_order'), name='uniq_community_post_media_slot')],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='trips.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='uniq_community_post_view_per_user')],
            },
        ),
    ]
