# Generated by Django 6.0.2 on 2026-08-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0017_login_throttle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypostreaction",
            name="reaction",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("love", "Love"),
                    ("care", "Care"),
                    ("wow", "Wow"),
                    ("helpful", "Helpful"),
                ],
                default="like",
                max_length=20,
            ),
        ),
    ]
